#!/bin/bash
#SBATCH --job-name=user
#SBATCH --mail-user=chenxgu@umich.edu
#SBATCH --mail-type=BEGIN,END
#SBATCH --time=100:00:00
#SBATCH --account=mihalcea1
#SBATCH --gres=gpu:1
#SBATCH --partition=gpu
#SBATCH --output=/scratch/mihalcea_root/mihalcea1/chenxgu/for_greatlakes/100_users/ppl-scripts/validation-no-embedding-awd-lstm-lm-finetune-on-validation-and-anchor-two-step-1000000/output.txt
#SBATCH --nodes=1
#SBATCH --mem-per-cpu=4g

#cd /home/chenxgu
export PATH=/home/chenxgu/anaconda3/bin:$PATH
source /home/chenxgu/.bashrc
conda activate pytorch04
echo ${user}
python main.py --lr 3 --num_similar_users 5 --user_name ${user} --pretrained_model ../../user-embedding-scripts/anchor-no-embedding-awd-lstm-lm/model_2.pt --num_training_tokens_from_validation 2000 --num_validation_tokens_from_validation 25000 --num_training_tokens_from_anchor 1000000 --data ../../data/250000_tokens_of_validation_users --pretrained_token_embedding '../../user-embedding-scripts/GloVe-1.2-emsize-200/GloVe_200' --freeze_parameters --token_emsize 200 --batch_size 20 --dropouti 0.2 --dropouth  0.2 --dropout 0.2 --dropoute 0.1 --seed 20190930 --epoch 500 --nhid 1150 --save model_${user}.pt > model_${user}.log
